server:
  port: 8080

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:db/migrations
    baseline-on-migrate: true
    repair-on-migrate: true
    schemas: orders

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: orders

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    service-url:
      defaultZone: http://eureka-container:8761/eureka/

management:
  endpoints:
    web:
      base-path: /order/actuator
      exposure:
        include: ['prometheus', 'health']